In [1]:
# 🏀 Building Your First Matrix in Python 🏀
# Let's explore how to work with matrices using NumPy.

# Importing NumPy 📦
import numpy as np

# Creating a Simple Matrix 📋
# Example: A 3x3 matrix with integers
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# Display the matrix
print("Our 3x3 Matrix:")
print(matrix)

# 🧩 Accessing Matrix Elements (Indexing)
# Access element at row 2, column 3
element = matrix[1, 2]  # Remember: Python indexing starts at 0
print("\nElement at Row 2, Column 3:", element)

# 🔪 Slicing the Matrix
# Extract first two rows and first two columns
sliced_matrix = matrix[:2, :2]
print("\nSliced Matrix (First 2 Rows, First 2 Columns):")
print(sliced_matrix)

# 🔄 Reshaping a Matrix
# Reshape the 3x3 matrix into a 1x9 array
reshaped_matrix = matrix.reshape(1, 9)
print("\nReshaped Matrix (1x9):")
print(reshaped_matrix)

# 🔢 Generating Matrices
# Create a 4x4 matrix filled with zeros
zeros_matrix = np.zeros((4, 4))
print("\n4x4 Zero Matrix:")
print(zeros_matrix)

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

# ⚙️ Performing Matrix Operations
# Define two matrices
matrix_a = np.array([[1, 2], 
                     [3, 4]])

matrix_b = np.array([[5, 6], 
                     [7, 8]])

# Add the matrices ➕
sum_matrix = matrix_a + matrix_b
print("\nMatrix Addition:")
print(sum_matrix)

# Multiply the matrices element-wise ✖️
product_matrix = matrix_a * matrix_b
print("\nElement-wise Matrix Multiplication:")
print(product_matrix)

# Dot product of the matrices 🔗
dot_product = np.dot(matrix_a, matrix_b)
print("\nMatrix Dot Product:")
print(dot_product)

# 🌟 Advanced Example: Basketball Data 🏀
# Creating a matrix to store player stats
points = np.array([[28, 24, 23, 22, 20],
                   [30, 27, 25, 24, 22],
                   [21, 19, 18, 17, 15]])

# Access points scored by the 2nd player in the 3rd game
player_2_game_3 = points[1, 2]
print("\nPoints scored by Player 2 in Game 3:", player_2_game_3)

# Calculate the average points scored per player
average_points = points.mean(axis=1)  # Average along rows
print("\nAverage Points Per Player:")
print(average_points)

# Transposing the matrix 🔄
transposed_points = points.T
print("\nTransposed Matrix (Games as Rows):")
print(transposed_points)

# 💡 Exercise: Try creating a 5x5 matrix and perform basic operations on it!

Our 3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at Row 2, Column 3: 6

Sliced Matrix (First 2 Rows, First 2 Columns):
[[1 2]
 [4 5]]

Reshaped Matrix (1x9):
[[1 2 3 4 5 6 7 8 9]]

4x4 Zero Matrix:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix Addition:
[[ 6  8]
 [10 12]]

Element-wise Matrix Multiplication:
[[ 5 12]
 [21 32]]

Matrix Dot Product:
[[19 22]
 [43 50]]

Points scored by Player 2 in Game 3: 25

Average Points Per Player:
[23.4 25.6 18. ]

Transposed Matrix (Games as Rows):
[[28 30 21]
 [24 27 19]
 [23 25 18]
 [22 24 17]
 [20 22 15]]
