In [1]:
# 🧮 Matrix Operations with NumPy - Python Lecture Notebook
# ===========================================
# In this lecture, we'll explore matrix operations using NumPy.
# Let's dive into the concepts and perform operations step by step! 🚀

# Importing the NumPy library
import numpy as np

# ------------------------------
# 🟢 1. Creating Matrices
# ------------------------------

# Creating Matrix A
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print("Matrix A:")
print(matrix_a)

# Creating Matrix B
matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])
print("\nMatrix B:")
print(matrix_b)

# ------------------------------
# 🟢 2. Basic Matrix Operations
# ------------------------------

# Matrix Addition
matrix_sum = matrix_a + matrix_b
print("\nMatrix Addition:")
print(matrix_sum)

# Matrix Subtraction
matrix_diff = matrix_a - matrix_b
print("\nMatrix Subtraction:")
print(matrix_diff)

# ------------------------------
# 🟢 3. Element-wise Operations
# ------------------------------

# Element-wise Multiplication
matrix_mult = matrix_a * matrix_b
print("\nElement-wise Multiplication:")
print(matrix_mult)

# Element-wise Division
matrix_div = matrix_a / matrix_b
print("\nElement-wise Division:")
print(matrix_div)

# ------------------------------
# 🟢 4. Matrix Multiplication (Dot Product)
# ------------------------------

# Matrix Multiplication using np.dot
matrix_product = np.dot(matrix_a, matrix_b)
print("\nMatrix Multiplication (Dot Product):")
print(matrix_product)

# Using the '@' operator for the same result
matrix_product_alt = matrix_a @ matrix_b
print("\nMatrix Multiplication (Using '@'):")
print(matrix_product_alt)

# ------------------------------
# 🟢 5. Scalar Operations
# ------------------------------

# Multiply Matrix A by 2
scalar_mult = matrix_a * 2
print("\nMatrix A multiplied by 2:")
print(scalar_mult)

# Add 5 to all elements in Matrix A
scalar_add = matrix_a + 5
print("\nMatrix A with 5 added:")
print(scalar_add)

# ------------------------------
# 🟢 6. Transposing a Matrix
# ------------------------------

# Transpose of Matrix A
matrix_transpose = matrix_a.T
print("\nTranspose of Matrix A:")
print(matrix_transpose)

# ------------------------------
# 🟢 7. Accessing Elements in Matrices
# ------------------------------

# Access the element at row 1, column 2
element = matrix_a[1, 2]
print("\nElement at (1, 2):", element)

# Access the first row
row = matrix_a[0, :]
print("First row of Matrix A:", row)

# Access the second column
column = matrix_a[:, 1]
print("Second column of Matrix A:", column)

# ------------------------------
# 🟢 8. Matrix Statistics
# ------------------------------

# Sum of all elements
matrix_sum_total = np.sum(matrix_a)
print("\nSum of all elements in Matrix A:", matrix_sum_total)

# Mean of the matrix
matrix_mean = np.mean(matrix_a)
print("Mean of Matrix A:", matrix_mean)

# Maximum and Minimum values
matrix_max = np.max(matrix_a)
matrix_min = np.min(matrix_a)
print("Maximum value in Matrix A:", matrix_max)
print("Minimum value in Matrix A:", matrix_min)

# ------------------------------
# 🟢 9. Advanced Matrix Operations
# ------------------------------

# Creating a square matrix
square_matrix = np.array([[2, 1],
                          [1, 3]])

# Determinant of the matrix
determinant = np.linalg.det(square_matrix)
print("\nDeterminant of the square matrix:", determinant)

# Inverse of the matrix
if determinant != 0:
    inverse = np.linalg.inv(square_matrix)
    print("Inverse of the square matrix:")
    print(inverse)
else:
    print("Matrix is singular, no inverse exists.")

# ------------------------------
# 🏀 Mini Project: Basketball Stats
# ------------------------------

# Field Goals and Games matrices
FieldGoals = np.array([[978, 775, 800],
                       [716, 743, 432]])

Games = np.array([[80, 77, 82],
                  [82, 79, 76]])

# Calculate Field Goals Per Game
FieldGoalsPerGame = np.round(FieldGoals / Games, 2)
print("\nField Goals Per Game:")
print(FieldGoalsPerGame)

# Access specific stats
print("\nPlayer 1's stats for year 2 (Field Goals Per Game):", FieldGoalsPerGame[0, 1])

# ------------------------------
# 🎉 Summary
# ------------------------------
# You've successfully explored matrix operations:
# - Basic arithmetic
# - Scalar operations
# - Dot product and transposition
# - Statistical operations
# - Real-world application with basketball data!

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Element-wise Division:
[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]

Matrix Multiplication (Dot Product):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix Multiplication (Using '@'):
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix A multiplied by 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix A with 5 added:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Element at (1, 2): 6
First row of Matrix A: [1 2 3]
Second column of Matrix A: [2 5 8]

Sum of all elements in Matrix A: 45
Mean of Matrix A: 5.0
Maximum value in Matrix A: 9
Minimum value in Matrix A: 1

Determinant of the square matrix: 5.000000000000001
Inverse o