In [2]:


# 🔍 **1. What is Array Slicing?**
# Slicing in NumPy allows us to extract parts of an array using indexing.
# It's super-efficient and very similar to slicing Python lists.

import numpy as np

# 🚀 **2. Creating a Sample Array**
# Let's create a 1D and 2D array to explore slicing.

# ➡️ 1D Array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

# ➡️ 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", arr2)

# ✂️ **3. Slicing in 1D Arrays**

# ➡️ Extract elements from index 1 to 3 (exclusive)
print("\nSlice 1D (1:4):", arr1[1:4])

# ➡️ Slice with a step
print("Slice 1D with step (0:5:2):", arr1[0:5:2])

# ➡️ Reverse the array
print("Reverse 1D Array:", arr1[::-1])

# ✂️ **4. Slicing in 2D Arrays**

# ➡️ Extract a single row (row 1)
print("\nRow 1 of 2D Array:", arr2[1])

# ➡️ Extract a single element (row 2, col 3)
print("Element at (2, 3):", arr2[1, 2])

# ➡️ Extract multiple rows and columns
print("Slice rows 1-3, columns 1-2:\n", arr2[0:2, 1:3])

# ➡️ Slice all rows but specific columns
print("All rows, columns 1-2:\n", arr2[:, 1:3])

# ✂️ **5. Modifying Slices**

# ➡️ Create a new array
arr = np.array([10, 20, 30, 40, 50])
print("\nOriginal Array:", arr)

# ➡️ Modify a slice
arr[1:4] = [200, 300, 400]
print("Modified Array:", arr)

# ⚠️ **Note**: Modifying a slice affects the original array unless `.copy()` is used.

# 🧪 **6. Slicing with Copy**

# ➡️ Create a copy to prevent original modification
arr_copy = arr[1:4].copy()
arr_copy[0] = 999
print("\nCopy of Slice Modified:", arr_copy)
print("Original Array Unaffected:", arr)

# 🔄 **7. Advanced 2D Slicing**

# ➡️ Extract all elements in column 1
print("\nColumn 1 of 2D Array:", arr2[:, 0])

# ➡️ Extract diagonal elements
print("Diagonal Elements:", arr2.diagonal())

# ➡️ Modify part of a 2D array
arr2[0:2, 0:2] = [[100, 200], [300, 400]]
print("\nModified 2D Array:\n", arr2)

# 🌟 **8. Summary of Slicing**

# - Slicing is an efficient way to extract subsets of arrays.
# - You can combine slicing with indexing to access or modify elements.
# - Use `.copy()` to prevent changes to the original array.

print("\n🎉 Congratulations! You've mastered slicing in NumPy!")


1D Array: [10 20 30 40 50]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Slice 1D (1:4): [20 30 40]
Slice 1D with step (0:5:2): [10 30 50]
Reverse 1D Array: [50 40 30 20 10]

Row 1 of 2D Array: [4 5 6]
Element at (2, 3): 6
Slice rows 1-3, columns 1-2:
 [[2 3]
 [5 6]]
All rows, columns 1-2:
 [[2 3]
 [5 6]
 [8 9]]

Original Array: [10 20 30 40 50]
Modified Array: [ 10 200 300 400  50]

Copy of Slice Modified: [999 300 400]
Original Array Unaffected: [ 10 200 300 400  50]

Column 1 of 2D Array: [1 4 7]
Diagonal Elements: [1 5 9]

Modified 2D Array:
 [[100 200   3]
 [300 400   6]
 [  7   8   9]]

🎉 Congratulations! You've mastered slicing in NumPy!
