In [1]:
# 📘 Lecture: NumPy and Arrays in Python

# 🔍 **1. What is NumPy?**
# NumPy (Numerical Python) is a powerful library for numerical computations in Python.
# It provides high-performance multidimensional arrays and tools to manipulate them.

# ✅ **Let's get started by importing NumPy**:
import numpy as np

# 🚀 **2. Creating Arrays**
# NumPy arrays are more efficient than Python lists for numerical operations.

# ➡️ Creating a 1D array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

# ➡️ Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# ➡️ Special Arrays
zeros = np.zeros((2, 3))  # Array of zeros
ones = np.ones((3, 3))    # Array of ones
identity = np.eye(4)      # Identity matrix
random_arr = np.random.rand(2, 4)  # Random array

print("\nZeros Array:\n", zeros)
print("\nOnes Array:\n", ones)
print("\nIdentity Matrix:\n", identity)
print("\nRandom Array:\n", random_arr)

# 🌟 **3. Array Properties**
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("\nArray Shape:", arr.shape)  # (rows, columns)
print("Array Dimensions:", arr.ndim)  # Number of dimensions
print("Array Size:", arr.size)  # Total number of elements
print("Array Data Type:", arr.dtype)  # Type of elements

# ✂️ **4. Indexing and Slicing**
# ➡️ Accessing elements in a 1D array
print("\nElement at index 1:", arr1[1])  # 20

# ➡️ Slicing in 1D arrays
print("Sliced Array (1:4):", arr1[1:4])  # [20, 30, 40]

# ➡️ Accessing elements in a 2D array
print("\nElement at (1,2):", arr2[0, 1])  # 2
print("Slice rows 1-2, cols 1-2:\n", arr2[0:2, 0:2])

# 🔢 **5. Array Arithmetic**
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# ➡️ Element-wise operations
print("\nAddition:", a + b)  # [5, 7, 9]
print("Multiplication:", a * b)  # [4, 10, 18]

# ➡️ Scalar operations
print("Scalar Multiplication:", a * 10)  # [10, 20, 30]

# ➡️ Conditional Filtering
filtered = arr1[arr1 > 20]
print("\nFiltered Array (arr1 > 20):", filtered)

# 🔄 **6. Reshaping Arrays**
# ➡️ Reshape a 1D array into 2D
reshaped = np.arange(1, 13).reshape(3, 4)  # 3 rows, 4 columns
print("\nReshaped Array:\n", reshaped)

# 📊 **7. Useful Functions**
print("\nSum of elements:", np.sum(reshaped))
print("Mean value:", np.mean(reshaped))
print("Max value:", np.max(reshaped))
print("Min value:", np.min(reshaped))

# 🌈 **8. Broadcasting**
# Broadcasting allows NumPy to perform operations on arrays of different shapes.
row = np.array([1, 2, 3])
column = np.array([[10], [20], [30]])
result = row + column  # Broadcasting adds row to each column
print("\nBroadcasted Result:\n", result)

# 🧮 **9. Matrix Operations**
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print("\nMatrix Addition:\n", matrix_a + matrix_b)
print("Matrix Multiplication:\n", np.dot(matrix_a, matrix_b))  # Dot product

# 🔥 **10. Summary**
# - NumPy arrays are more efficient than Python lists for numerical computations.
# - They support various operations like indexing, slicing, reshaping, and broadcasting.
# - NumPy is essential for data science, machine learning, and numerical tasks.

print("\n🎉 Congratulations! You've completed the NumPy lecture.")

1D Array: [10 20 30 40 50]

2D Array:
 [[1 2 3]
 [4 5 6]]

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Array:
 [[0.76950718 0.28094629 0.48485881 0.89338494]
 [0.0795389  0.36899819 0.26987527 0.89950784]]

Array Shape: (2, 3)
Array Dimensions: 2
Array Size: 6
Array Data Type: int32

Element at index 1: 20
Sliced Array (1:4): [20 30 40]

Element at (1,2): 2
Slice rows 1-2, cols 1-2:
 [[1 2]
 [4 5]]

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Scalar Multiplication: [10 20 30]

Filtered Array (arr1 > 20): [30 40 50]

Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sum of elements: 78
Mean value: 6.5
Max value: 12
Min value: 1

Broadcasted Result:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]

🎉 Congratulations! You've completed the NumPy lecture.
